name: test

on:
  workflow_call:

jobs:
  test:
    name: rspec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.4', '4.0']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: sorah-rbpkg/actions@bcd0417f7e6e66bf85a51bf49f323ad4db3bfb12 # v3.0.1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: 'bundle exec rspec -fd'

  integration-pebble:
    name: integration-pebble
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.4', '4.0']

        # FIXME: once GitHub Actions gains support of adding command line arguments to container
      #    services:
      #      # https://github.com/letsencrypt/pebble
      #      pebble:
      #        image: letsencrypt/pebble
      #        ports:
      #          - 14000:14000  # ACME port
      #          - 15000:15000  # Management port
      #        options: "pebble -config /test/config/pebble-config.json -strict -dnsserver 127.0.0.1:8053"
      #
      #      challtestsrv:
      #        image: letsencrypt/pebble-challtestsrv:latest
      #        ports:
      #          - 8055:8055  # HTTP Management API
      #          - 8053:8053/udp # DNS
      #          - 8053:8053 # DNS
      #        options: 'pebble-challtestsrv -management :8055 -defaultIPv4 127.0.0.1'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: sorah-rbpkg/actions@bcd0417f7e6e66bf85a51bf49f323ad4db3bfb12 # v3.0.1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true

      - run: 'docker run -d --net=host --rm ghcr.io/letsencrypt/pebble:2.10 -config /test/config/pebble-config.json -strict -dnsserver 127.0.0.1:8053'
      - run: 'docker run -d --net=host --rm ghcr.io/letsencrypt/pebble-challtestsrv:2.10 -management :8055 -defaultIPv4 127.0.0.1'
      - run: 'bundle exec rspec -fd -t integration_pebble'
