name: ci
on:
  schedule:
    - cron: '36 7 2,12,22 * *'
  push:
    branches: [master, ci-test]

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  docker:
    needs: [test]
    uses: ./.github/workflows/_docker.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
