name: ci
on:
  schedule:
    - cron: '36 7 2,12,22 * *'
  create: {}
  push:
    branches: [master, ci-test]

env:
  DOCKER_REPO: 'sorah/acmesmith'

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: 'echo $GITHUB_SHA > REVISION'

      - run: "docker pull ${DOCKER_REPO}:latest || :"
      - name: "docker tag ${DOCKER_REPO}:${TAG} ${DOCKER_REPO}:latest"
        run: |
          TAG=$(basename "${{ github.ref }}")
          docker pull ${DOCKER_REPO}:${TAG} || :
          docker tag ${DOCKER_REPO}:${TAG} ${DOCKER_REPO}:latest || :
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"

      - run: "docker pull ${DOCKER_REPO}:builder || :"

      - run: "docker build --pull --cache-from ${DOCKER_REPO}:builder --target builder -t ${DOCKER_REPO}:builder -f Dockerfile ."
      - run: "docker build --pull --cache-from ${DOCKER_REPO}:builder --cache-from ${DOCKER_REPO}:latest -t ${DOCKER_REPO}:${GITHUB_SHA} -f Dockerfile ."

      - run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"

      - run: "docker push ${DOCKER_REPO}:builder"
        if: "${{ github.ref == 'refs/heads/master' }}"
      - run: "docker push ${DOCKER_REPO}:${GITHUB_SHA}"

  docker-push:
    name: docker-push
    needs: [test, docker-build]
    runs-on: ubuntu-latest
    steps:
      - run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"
      - run: "docker pull ${DOCKER_REPO}:${GITHUB_SHA}"

      - run: |
          docker tag ${DOCKER_REPO}:${GITHUB_SHA} ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO}:latest
        if: "${{ github.ref == 'refs/heads/master' }}"
      - run: |
          TAG=$(basename "${{ github.ref }}")
          docker tag ${DOCKER_REPO}:${GITHUB_SHA} ${DOCKER_REPO}:${TAG}
          docker push ${DOCKER_REPO}:${TAG}
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
