on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  docker:
    needs: [test]
    uses: ./.github/workflows/_docker.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  release:
    needs: [test]
    runs-on: ubuntu-slim
    environment:
      name: release
      url: https://rubygems.org/gems/acmesmith
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@4eb9f110bac952a8b68ecf92e3b5c7a987594ba6 # v1.292.0
        with:
          bundler-cache: 'true'
          ruby-version: '4.0.1'
      - name: Create GitHub release
        run: |
          tag_name="$(git describe --tags --abbrev=0)"
          gh release create "${tag_name}" --verify-tag --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to RubyGems
        uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169 # v1.1.4
